# Generated by Django 5.1.7 on 2025-04-30 15:47

from django.db import migrations

def update_profile_images(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    for profile in Profile.objects.all():
        if profile.image == 'profile.jpg':
            profile.image = 'profile_pics/profile.jpg'
            profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.RunPython(update_profile_images),
    ]
