# Generated by Django 5.1.7 on 2025-03-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://metropizza.com.au/wp-content/uploads/2023/06/food-placeholder.jpeg', max_length=500),
        ),
    ]
